---
- name: Configure vCenter Global Administrator Permission
  hosts: localhost
  gather_facts: no
  
  vars:
    vcenter_hostname: "vcsa.vclass.kh"
    vcenter_username: "administrator@vsphere.kh"
    vcenter_password: "VMware1!"
    vcenter_validate_certs: false
    admin_group: "students@vclass.kh"
    
  tasks:
    - name: Remove Administrator permission for Global Inventory
      community.vmware.vmware_object_role_permission:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        role: "Admin"
        principal: students@vclass.kh
        group: true
        object_type: "{{ item.type }}"
        object_name: "{{ item.path }}"
        recursive: true
        state: absent
      loop:
        - { type: 'Datacenter', path: '/' }  # Datacenter 객체
        - { type: 'Folder', path: '/vm' }    # VM 및 템플릿
        - { type: 'Folder', path: '/host' }  # 호스트 및 클러스터
        - { type: 'Folder', path: '/datastore' }  # 데이터스토어
        - { type: 'Folder', path: '/network' }    # 네트워크
